from __future__ import annotations

from typing import Any

PALETTE: dict[str, list[dict[str, Any]]] = {
    "Speed": [
        {
            "type": "value",
            "label": "Speed",
            "binding": "vehicle.speed_kmh",
            "fallback_bindings": ["vehicle.speed_kmh_backup"],
            "value_style": "digital",
            "min_value": 0,
            "max_value": 220,
            "prefix": "",
            "suffix": "",
            "font_size": 120,
        },
        {
            "type": "value",
            "label": "Speed bar",
            "binding": "vehicle.speed_kmh",
            "fallback_bindings": ["vehicle.speed_kmh_backup"],
            "value_style": "bar",
            "min_value": 0,
            "max_value": 220,
            "prefix": "",
            "suffix": " km/h",
            "font_size": 32,
            "accent": "#24d36b",
            "inactive_color": "#1a2430",
        },
        {
            "type": "value",
            "label": "Speed needle",
            "binding": "vehicle.speed_kmh",
            "fallback_bindings": ["vehicle.speed_kmh_backup"],
            "value_style": "needle",
            "min_value": 0,
            "max_value": 220,
            "tick_interval": 20,
            "prefix": "",
            "suffix": " km/h",
            "font_size": 30,
            "accent": "#24d36b",
            "inactive_color": "#1a2430",
        },
        {
            "type": "value",
            "label": "Speed analog",
            "binding": "vehicle.speed_kmh",
            "fallback_bindings": ["vehicle.speed_kmh_backup"],
            "value_style": "analog",
            "min_value": 0,
            "max_value": 220,
            "tick_interval": 20,
            "prefix": "",
            "suffix": " km/h",
            "font_size": 30,
            "accent": "#24d36b",
            "inactive_color": "#1a2430",
        },
    ],
    "Gear": [
        {
            "type": "gear_indicator",
            "label": "Gear strip",
            "binding": "vehicle.gear_range",
            "gears": ["P", "R", "N", "D", "3", "2", "L"],
            "gear_style": "strip",
            "font_size": 28,
            "active_font_size": 92,
            "accent": "#24d36b",
            "inactive_color": "#4a5568",
        },
        {
            "type": "gear_indicator",
            "label": "Gear active",
            "binding": "vehicle.gear_range",
            "gears": ["P", "R", "N", "D", "3", "2", "L"],
            "gear_style": "active_only",
            "font_size": 36,
            "active_font_size": 118,
            "accent": "#24d36b",
            "inactive_color": "#4a5568",
        },
    ],
    "RPM": [
        {
            "type": "value",
            "label": "RPM",
            "binding": "vehicle.rpm",
            "value_style": "digital",
            "min_value": 0,
            "max_value": 8000,
            "prefix": "RPM ",
            "suffix": "",
            "font_size": 36,
        },
        {
            "type": "value",
            "label": "RPM sport",
            "binding": "vehicle.rpm",
            "value_style": "sport_gauge",
            "min_value": 0,
            "max_value": 8000,
            "tick_interval": 1000,
            "prefix": "",
            "suffix": " rpm",
            "font_size": 40,
            "accent": "#24d36b",
            "redline_color": "#ff3b30",
            "inactive_color": "#1a2430",
        },
    ],
    "Temperature": [
        {"type": "value", "label": "Coolant", "binding": "vehicle.coolant_c", "value_style": "digital", "min_value": -40, "max_value": 130, "suffix": "°C", "font_size": 32},
        {"type": "value", "label": "ATF", "binding": "vehicle.atf_c", "value_style": "digital", "min_value": -40, "max_value": 160, "prefix": "ATF ", "suffix": "°C", "font_size": 30},
    ],
    "Power/Fuel": [
        {"type": "value", "label": "Voltage", "binding": "vehicle.voltage_v", "value_style": "digital", "min_value": 0, "max_value": 16, "suffix": "V", "font_size": 32},
        {"type": "value", "label": "Fuel", "binding": "vehicle.fuel_percent", "value_style": "bar", "min_value": 0, "max_value": 100, "prefix": "Fuel ", "suffix": "%", "font_size": 32},
        {"type": "value", "label": "Fuel value", "binding": "vehicle.fuel_percent", "value_style": "digital", "min_value": 0, "max_value": 100, "prefix": "FUEL ", "suffix": "%", "font_size": 28},
    ],
    "Driver Input": [
        {"type": "value", "label": "Backup speed", "binding": "vehicle.speed_kmh_backup", "value_style": "digital", "min_value": 0, "max_value": 220, "prefix": "GPS ", "suffix": " km/h", "font_size": 30},
        {"type": "value", "label": "Actual gear", "binding": "vehicle.gear_actual", "prefix": "G ", "font_size": 30},
        {"type": "value", "label": "Pedal", "binding": "vehicle.pedal_percent", "value_style": "bar", "min_value": 0, "max_value": 100, "prefix": "PED ", "suffix": "%", "font_size": 30},
    ],
    "Navigation": [
        {"type": "nav_icon", "label": "Turn icon", "event_binding": "nav.event_type", "side_binding": "nav.turn_side", "font_size": 32},
        {"type": "value", "label": "Instruction", "binding": "nav.instruction", "font_size": 32},
        {"type": "value", "label": "Road", "binding": "nav.road", "font_size": 30},
        {"type": "value", "label": "Next distance", "binding": "nav.distance_meters", "suffix": " m", "font_size": 28},
        {"type": "value", "label": "Nav state", "binding": "nav.connected", "prefix": "NAV ", "font_size": 28},
    ],
    "Warning Lamps": [
        {"type": "warning_icon", "label": "Door open", "binding": "warnings.door_open", "icon": "door_open", "font_size": 22},
        {"type": "warning_icon", "label": "Battery", "binding": "warnings.battery", "icon": "battery", "font_size": 22},
        {"type": "warning_icon", "label": "Brake", "binding": "warnings.brake", "icon": "brake", "font_size": 22},
        {"type": "warning_icon", "label": "ABS", "binding": "warnings.abs", "icon": "abs", "font_size": 22},
        {"type": "warning_icon", "label": "Airbag", "binding": "warnings.airbag", "icon": "airbag", "font_size": 22},
        {"type": "warning_icon", "label": "Oil", "binding": "warnings.oil_pressure", "icon": "oil_pressure", "font_size": 22},
        {"type": "warning_icon", "label": "Check engine", "binding": "warnings.check_engine", "icon": "check_engine", "font_size": 22},
        {"type": "warning_icon", "label": "EPS", "binding": "warnings.eps", "icon": "eps", "font_size": 22},
        {"type": "warning_icon", "label": "Coolant", "binding": "warnings.coolant_temp", "icon": "coolant_temp", "font_size": 22},
        {"type": "warning_icon", "label": "Seatbelt", "binding": "warnings.seatbelt", "icon": "seatbelt", "font_size": 22},
        {"type": "warning_icon", "label": "Low fuel", "binding": "warnings.low_fuel", "icon": "low_fuel", "font_size": 22},
        {"type": "warning_icon", "label": "Tire pressure", "binding": "warnings.tire_pressure", "icon": "tire_pressure", "font_size": 22},
        {"type": "warning_icon", "label": "High beam", "binding": "warnings.high_beam", "icon": "high_beam", "font_size": 22},
        {"type": "warning_icon", "label": "Low beam", "binding": "warnings.low_beam", "icon": "low_beam", "font_size": 22},
        {"type": "warning_icon", "label": "Parking lights", "binding": "warnings.parking_lights", "icon": "parking_lights", "font_size": 22},
        {"type": "warning_icon", "label": "Fog light", "binding": "warnings.fog_light", "icon": "fog_light", "font_size": 22},
        {"type": "warning_icon", "label": "Washer fluid", "binding": "warnings.washer_fluid", "icon": "washer_fluid", "font_size": 22},
        {"type": "warning_icon", "label": "Cruise control", "binding": "warnings.cruise_control", "icon": "cruise_control", "font_size": 22},
        {"type": "warning_icon", "label": "Traction control", "binding": "warnings.traction_control", "icon": "traction_control", "font_size": 22},
        {"type": "warning_icon", "label": "Glow plug", "binding": "warnings.glow_plug", "icon": "glow_plug", "font_size": 22},
    ],
    "DTC": [
        {"type": "value", "label": "DTC count", "binding": "dtc.count", "prefix": "DTC ", "font_size": 30},
        {"type": "value", "label": "MIL", "binding": "dtc.mil", "prefix": "MIL ", "font_size": 30},
    ],
    "Weather": [
        {"type": "value", "label": "Weather temp", "binding": "weather.temp_c", "suffix": "°C", "font_size": 34},
        {"type": "value", "label": "Feels like", "binding": "weather.apparent_c", "prefix": "FEELS ", "suffix": "°C", "font_size": 28},
        {"type": "value", "label": "Weather condition", "binding": "weather.condition_ko", "fallback_bindings": ["weather.condition"], "font_size": 28},
        {"type": "value", "label": "Weather wind", "binding": "weather.wind_kmh", "prefix": "WIND ", "suffix": " km/h", "font_size": 26},
        {"type": "value", "label": "Weather location", "binding": "weather.location_name", "font_size": 24},
    ],
    "Input Diagnostics": [
        {"type": "value", "label": "Vehicle source", "binding": "vehicle.source", "prefix": "SRC ", "font_size": 28},
        {"type": "value", "label": "OBD state", "binding": "vehicle.obd_state", "prefix": "OBD ", "font_size": 28},
        {"type": "value", "label": "CAN state", "binding": "vehicle.can_state", "prefix": "CAN ", "font_size": 28},
        {"type": "value", "label": "CAN frames", "binding": "debug.can_frame_count", "prefix": "CAN #", "font_size": 28},
        {"type": "value", "label": "Last CAN ID", "binding": "debug.last_can_id", "prefix": "ID ", "font_size": 28},
        {"type": "value", "label": "OBD request", "binding": "debug.obd_request", "prefix": "REQ ", "font_size": 26},
        {"type": "value", "label": "OBD response", "binding": "debug.obd_response", "prefix": "RESP ", "font_size": 24},
        {"type": "value", "label": "Stored DTC", "binding": "dtc.stored", "prefix": "STORED ", "font_size": 26},
        {"type": "value", "label": "Pending DTC", "binding": "dtc.pending", "prefix": "PENDING ", "font_size": 26},
        {"type": "value", "label": "Permanent DTC", "binding": "dtc.permanent", "prefix": "PERM ", "font_size": 26},
    ],
    "Labels": [
        {"type": "text", "label": "Text label", "text": "LABEL", "font_size": 32},
    ],
}
